name: Weekly Container Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs at midnight on Sunday

jobs:
  copybara-build:
    runs-on: depot-ubuntu-24.04
    permissions:
      contents: read # required for checkout
      id-token: write # mint AWS credentials through OIDC
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: depot/setup-action@v1
      - name: Bake container
        uses: depot/bake-action@v1.10.0
        id: bake
        with:
          project: xnsnw3m20t
          files: images-bake.hcl
          sbom: true
          push: true